// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdltxympgajlnwzwibcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbHR4eW1wZ2FqbG53endpYmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODYwMDEsImV4cCI6MjA3MTE2MjAwMX0.E0pgyYv65DfOPCkiqKFDXiGqYDp3SwXNaRcWGVOILdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});